AllCops:
  Exclude:
    - 'Gemfile'
    - 'app/channels/application_cable/**/*'
    - 'db/**/*'
    - 'bin/bundle'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/BlockComments:
  EnforcedStyle: line_count_based

Style/SingleArgumentDig:
  Enabled: false

Style/Documentation:
  Enabled: false
